version: "3"

services:
  webapp:
    build: ./webapp
    ports:
      - "8081:80"
    #volumes:
    #  - chimera-vol:/opt/chimera/data
  cliapp:
    build: ./cliapp
    #volumes:
    #  - chimera-vol:/opt/chimera/data
  redis:
    image: "redis:latest"
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  
#volumes:
#  chimera-vol:
  